#
# Copyright the State of the Netherlands
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see http://www.gnu.org/licenses/.
#

version: "3"

services:
  traefik:
    image: traefik:v2.2
    command:
      - "--log.level=DEBUG"
      - "--api.insecure=true"
      - "--providers.docker.endpoint=unix:///var/run/docker.sock"
      - "--providers.docker.swarmMode=true"
      - "--providers.docker.exposedbydefault=false"
      - "--providers.docker.network=web"
      - "--entrypoints.web.address=:80"
    ports:
      - 80:80
#      - 4001:8080
    volumes:
      # So that Traefik can listen to the Docker events
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - web

  tetris-service:
    deploy:
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.tetris-local-service-data.rule=(Host(`localhost`) || Host(`127.0.0.1`)) && PathPrefix(`/tetris/`)"
        - "traefik.http.routers.tetris-local-service-data.middlewares=tetris-local-service-data-stripprefix"
        - "traefik.http.routers.tetris-local-service-data.entrypoints=web"
        - "traefik.http.services.tetris-local-service-data.loadbalancer.server.port=8090"
        - "traefik.http.middlewares.tetris-local-service-data-stripprefix.stripprefix.prefixes=/tetris/"
    networks:
      - web

networks:
  web:
    external: true
