server:
  port: 8090
  
spring:
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: create
  datasource:
    #url: jdbc:h2:file:~/data/tetris-leaderboard
    
    driverClassName: org.h2.Driver
    username: aerius
    password: aerius
    database-platform: org.hibernate.dialect.H2Dialect
